###

#GET http://swstime.chinasws.com:88/sws-mobile-app/app/user/list
#GET http://swstime.chinasws.com:88/sws-mobile-app/app/list
GET https://swstime.chinasws.com:18443/sws-mobile-app/app/list
#GET https://swstime.chinasws.com:18443/sws-mobile-app/app/info
#GET http://swstime.chinasws.com:88/sws-mobile-app/app/info
#GET https://demo.chinasws.com/sws-mobile-app/app/user/list
Authorization: Basic c2FiZXI6c2FiZXJfc2VjcmV0
Blade-Auth: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRfaWQiOiIwMDAwMDAiLCJ1c2VyX25hbWUiOiJhZG1pbiIsInJlYWxfbmFtZSI6IueuoeeQhuWRmCIsImF2YXRhciI6Imh0dHBzOi8vbW9iaWxlLmNoaW5hc3dzLmNvbS9zd3MtbW9iaWxlL3VwbG9hZC8yMDIwMTAyMi83NDJkYTBlZjlhYzJlNzk4Y2FlMzFkNjdjNzFjM2I2ZC5qcGciLCJhdXRob3JpdGllcyI6WyLlhazlj7jkuK3lsYIiLCJhZG1pbmlzdHJhdG9yIl0sImNsaWVudF9pZCI6InNhYmVyIiwicm9sZV9uYW1lIjoiYWRtaW5pc3RyYXRvcizlhazlj7jkuK3lsYIiLCJsaWNlbnNlIjoicG93ZXJlZCBieSBibGFkZXgiLCJwb3N0X2lkIjoiMTEyMzU5ODgxNzczODY3NTIwMSIsInVzZXJfaWQiOiIxMTIzNTk4ODIxNzM4Njc1MjAxIiwicm9sZV9pZCI6IjExMjM1OTg4MTY3Mzg2NzUyMDEsMTI5NDA4OTUwNzYyMjE0MTk1MyIsInNjb3BlIjpbImFsbCJdLCJuaWNrX25hbWUiOiLnrqHnkIblkZgiLCJvYXV0aF9pZCI6IiIsImV4cCI6MTYxNjA5MTgwNiwiZGVwdF9pZCI6IjEyODg3NjIzMDEwMTA1Nzk0NTciLCJqdGkiOiJlNWM4MzYxYS01MTZmLTRmYmYtOGJlYi04MjM1NDQzNWQ2MDIiLCJhY2NvdW50IjoiYWRtaW4ifQ.Ni8Xv5Ij_eRfFyTMMyRGwCzCLqgYk1yHEKMoEe82RxA